name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install
      working-directory: ./cvr-jp-apply
      run: bun install --frozen-lockfile
    - name: Build
      working-directory: ./cvr-jp-apply
      run: bun dist
    - name: Create Zip
      uses: thedoctor0/zip-release@0.7.6
      with:
        exclusions: |
          .*
          cvr-jp-apply
        filename: "cvr-jp-${{github.ref_name}}.zip"

    - name: Make Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          cvr-jp-${{github.ref_name}}.zip
